% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Oct-2023 09:29:05
%  MATLAB version: 9.12.0.2039608 (R2022a) Update 5
% -------------------------------------------------------------------
saveVarsMat = load('LINEAR.mat');

A = ...
  [1 1 1;
   1 2 2;
   1 2 3];

A1 = ...
  [5 6 8;
   1 2 2;
   1 2 3];

A2 = ...
  [1 1 1;
   5 6 8;
   1 2 3];

A3 = ...
  [1 1 1;
   1 2 2;
   5 6 8];

ans = 2;

eq1 = saveVarsMat.eq1; % <1x1 sym> unsupported class

eq2 = saveVarsMat.eq2; % <1x1 sym> unsupported class

eq3 = saveVarsMat.eq3; % <1x1 sym> unsupported class

sol = saveVarsMat.sol; % <1x1 struct> unsupported class at sol.x

x = saveVarsMat.x; % <1x1 sym> unsupported class

xsol = saveVarsMat.xsol; % <1x1 sym> unsupported class

y = saveVarsMat.y; % <1x1 sym> unsupported class

ysol = saveVarsMat.ysol; % <1x1 sym> unsupported class

z = saveVarsMat.z; % <1x1 sym> unsupported class

zsol = saveVarsMat.zsol; % <1x1 sym> unsupported class

clear saveVarsMat;
